export const settings = [
  {
    id: 1,
    dx: 3,
    dy: 15,
    rad: 15,
    color: "random",
    colorBorder: "green",
    background: "black",
    trace: false,
    move: null,
    bounce: null,
    numbers: 1000,
  },
  {
    id: 2,
    dx: 5,
    dy: 5,
    rad: 15,
    color: "rgba(0,0,0,0)",
    colorBorder: "random",
    background: "ivory",
    trace: true,
    move: null,
    bounce: null,
    numbers: 1000,
  },
  {
    id: 3,
    dx: 100,
    dy: 100,
    rad: 5,
    color: "rgba(0,0,0,0)",
    colorBorder: "random",
    background: "white",
    trace: true,
    move: "random",
    bounce: null,
    numbers: 500,
  },
];
